### PR TITLE
Enhanced Error Traceability

### PR DESCRIPTION
**Pull request by thmboyer**
Hello,

I'm currently developing a backend for obtaining certificates from Sectigo CA using Python 3.11. I've noticed that the current error handling for key errors in the configuration dictionary is not very intuitive, making it challenging to pinpoint the root cause.

I believe my modifications will improve error traceability in this scenario. If you find these changes beneficial, I'm more than willing to extend this approach to other areas.

### CODE REVIEW

**Comment by uedvt359** [comment]
Hi, thanks for your patch! I guess this looks OK, but can you please post a before and after output of the traceback?

**Comment by thmboyer** [comment]
Sure, here is what I get when using the openssl backend's config dictionary with the key 'NotOpenssl' instead of 'openssl'

**Before:**
```
Traceback (most recent call last):
  File "/root/totototo/serles-acme/serles/__main__.py", line 6, in <module>
    create_app().run(host="::0", port=8443, ssl_context="adhoc")
    ^^^^^^^^^^^^
  File "/root/totototo/serles-acme/serles/__init__.py", line 17, in create_app
    config, _ = get_config()
                ^^^^^^^^^^^^
  File "/root/totototo/serles-acme/serles/configloader.py", line 14, in get_config
    config, backend = load_config_and_backend(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/totototo/serles-acme/serles/configloader.py", line 59, in load_config_and_backend
    raise ConfigError(
serles.configloader.ConfigError: please define the backend class to use in [serles]backend=
```

**After:**
```
Traceback (most recent call last):
  File "/root/totototo/serles-acme/serles/configloader.py", line 56, in load_config_and_backend
    backend = getattr(backendModule, cls or "Backend")(cparser)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/totototo/serles-acme/serles/backends/openssl.py", line 6, in __init__
    self.cacert = config['NotOpenssl']['cacert']
                  ~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/configparser.py", line 979, in __getitem__
    raise KeyError(key)
KeyError: 'NotOpenssl'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/totototo/serles-acme/serles/__main__.py", line 6, in <module>
    create_app().run(host="::0", port=8443, ssl_context="adhoc")
    ^^^^^^^^^^^^
  File "/root/totototo/serles-acme/serles/__init__.py", line 17, in create_app
    config, _ = get_config()
                ^^^^^^^^^^^^
  File "/root/totototo/serles-acme/serles/configloader.py", line 14, in get_config
    config, backend = load_config_and_backend(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/totototo/serles-acme/serles/configloader.py", line 59, in load_config_and_backend
    raise ConfigError(
serles.configloader.ConfigError: please define the backend class to use in [serles]backend=
```

**Comment by uedvt359** [comment]
Oh, I see what is going on here. The code this try-catch is wrapping attempts to find problems with the config's keys and values, but accidentally also catches errors that happened while importing and initializing the backend. KeyError was supposed to only trigger on line 54; ModuleNotFound on line 55; and so on.

I have committed a more thorough fix to the `better-backend-exceptions` branch (https://github.com/dvtirol/serles-acme/compare/master...better-backend-exceptions) - would you mind trying this out if this would also work for you?

**Comment by thmboyer** [comment]
Thank you for providing the code. I've tested it out and it seems to work well. Just wanted to point out a small typo on line 62 where **from** should be replaced with **as**. Other than that, everything seems to be functioning as expected.

**Comment by uedvt359** [comment]
oops, fixed that (branch updated)! I added another check (wrong module loaded?), while i was looking at it. would you mind testing this again? if my proposed fix works for you, I'll merge it instead of this PR.

**Comment by uedvt359** [comment]
merged `better-backend-exceptions` into master. thanks for noticing this deficiency!

**Pull request closed without merging**
